# spring.cloud.config.uri=http://localhost:8888
# spring.application.name=gateway
# spring.profiles.active=default
# spring.config.import=optional:configserver:http://localhost:8888/

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            - name: AuthenticationFilter
        - id: notifications
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/notifications/**
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
